-- Rename posts to ideas migration
-- This migration renames all post-related tables, columns, indexes, and constraints to use "idea" terminology

-- Rename tables
ALTER TABLE "posts" RENAME TO "ideas";
ALTER TABLE "post_votes" RENAME TO "idea_votes";
ALTER TABLE "post_revisions" RENAME TO "idea_revisions";
ALTER TABLE "post_tags" RENAME TO "idea_tags";

-- Rename columns in comments table
ALTER TABLE "comments" RENAME COLUMN "post_id" TO "idea_id";

-- Rename columns in idea_votes table
ALTER TABLE "idea_votes" RENAME COLUMN "post_id" TO "idea_id";

-- Rename columns in idea_revisions table
ALTER TABLE "idea_revisions" RENAME COLUMN "post_id" TO "idea_id";

-- Rename columns in idea_tags table
ALTER TABLE "idea_tags" RENAME COLUMN "post_id" TO "idea_id";

-- Rename indexes on ideas table
ALTER INDEX "post_author_idx" RENAME TO "idea_author_idx";
ALTER INDEX "post_challenge_idx" RENAME TO "idea_challenge_idx";
ALTER INDEX "post_score_idx" RENAME TO "idea_score_idx";
ALTER INDEX "post_created_at_idx" RENAME TO "idea_created_at_idx";

-- Rename index on comments table
ALTER INDEX "comment_post_idx" RENAME TO "comment_idea_idx";

-- Rename index on idea_revisions table
ALTER INDEX "revision_post_idx" RENAME TO "revision_idea_idx";

-- Rename unique constraints
ALTER INDEX "post_user_vote_unique" RENAME TO "idea_user_vote_unique";
ALTER INDEX "post_tag_unique" RENAME TO "idea_tag_unique";

-- Note: Foreign key constraint names are auto-generated by PostgreSQL
-- and will automatically reference the correct renamed tables and columns
